name: Copy the report for DevSecOps Workflow for MyVodafoneApp
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Build Job is going on"
          sleep 20

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: |
          echo "test Job is going on"
          sleep 20

  oast-retire:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Clone the Repository
        uses: actions/checkout@v2

      - name: Install Retire.JS
        run: npm install -g retire

      - name: Install Node Modules
        run: npm install

      - name: run Retire.JS Scan
        run: | 
          retire > output.txt
        continue-on-error: true
      - name: download the json report
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: output.txt
        if: always()

  Validate:
    runs-on: ubuntu-latest
    needs: oast-retire
    steps:
      - name: download the file
        uses: actions/download-artifact@v2
        with:
          name: output
      - name: Validation if file is created
        run: cat output.txt

  deployment:
    runs-on: ubuntu-latest
    needs: oast-retire
    steps:
      - run: |
          echo "deployment Job is going on"
          sleep 10


