name: Report of Safety
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Build Job is going on"
          sleep 20

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: |
          echo "test Job is going on"
          sleep 20

  oast-retire:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Clone the Repository
        uses: actions/checkout@v2

      - name: Install Safety
        run: pip install safety

      - name: run Safety
        run: | 
          safety check -r requirements.txt --full-report --json -o safety_output.json
        continue-on-error: true
        
      - name: download the json report
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: output.json
        if: always()

  deployment:
    runs-on: ubuntu-latest
    needs: oast-retire
    steps:
      - run: |
          echo "deployment Job is going on"
          sleep 10
